### ISSUE TITLE
Open Ads Appear When Game Is In Loading Screen

### ISSUE THREAD

**Issue by kienpt96gamee** [pancake-llc/heart#20]
Pull Pin Out 3D has an issue that have not been fixed for a long time: Open Ads appear when loading bar in Loading Screen is not 100% yet, this causes a big problem. Sometimes, App Store reviews and refuses the new update becasue it doesn't allow ads appear before playing game (the first level indeed)

**Comment by yenmoc** [comment]
Fixed in v2
Test in Android (LDPlayer emualtor) : Passed
  - Tet with applovin and admob : Passed
Test in iOS ...
