### ISSUE TITLE
Không preview được vật thể có fx trong level editor

### ISSUE THREAD

**Issue by GuardianOfGods** [pancake-llc/heart#6]

**Comment by yenmoc** [comment]
hmm có vẻ là do fx cụ thể là particle cần select mới play, còn khi không select nó không play và preview là trống. Tôi sẽ kiểm tra lại trường hợp này

**Comment by HoangVanThu99** [comment]
![image (1)](https://user-images.githubusercontent.com/88299194/207507752-16955fef-3064-44df-a263-db2d2f841b40.png)
