### ISSUE TITLE
Bên Ios file AuthService.cs bị không nhận diện được thư viện

### ISSUE THREAD

**Issue by HoangVanThu99** [pancake-llc/heart#7]
<img width="1440" alt="Screen Shot 2022-12-14 at 11 42 25 AM" src="https://user-images.githubusercontent.com/88299194/207507822-bcbafe07-c910-4f59-8594-f86d6054a682.png">

**Comment by HoangVanThu99** [comment]
Phải thêm cái này mới dùng được
![Screen Shot 2022-12-14 at 11 42 25 AM](https://user-images.githubusercontent.com/88299194/207507962-1f39d43b-d097-48f2-bf36-130f60884aec.png)

**Comment by yenmoc** [comment]
[fixed](https://github.com/pancake-llc/heart/commit/3553a2bef664e6219c7c5821dce4b199adf973be)
